PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX ex:<http://www.tmr.qld.gov.au/-/media/aboutus/corpinfo/Open%20data/marinepollutiondata/a#>

SELECT ?id ?date ?region ?pollutant ?estimated
WHERE{ ?x ex:Id ?id.
	?x ex:Date ?date.
	?x dbo:city ?region.
	?x ex:Pollutant ?pollutant.
	?x ex:Estimated_Litres ?estimated.
	MINUS { ?x <http://www.tmr.qld.gov.au/-/media/aboutus/corpinfo/Open%20data/marinepollutiondata/a#Estimated_Litres> "Unknown".}
}
